### ISSUE TITLE
Provide example.

### ISSUE THREAD

**Issue by zambrovski** [holisticon/axon-cdi#1]
Implement example showing usage of the component

**Comment by alexmacavei** [comment]
Hey guys! Is this project still going? I'm very interested in it and I'm quite willing to give it a go to create an example. I'm just curious what state it's in, as the readme doesn't look very detailed yet.

**Comment by jangalinski** [comment]
We are currently “finalizing” this, features are complete (enough). But as you noticed, documentation, tests and examples are missing. Please feel free to provide an example pr.  Thanks, Jan

**Comment by alexmacavei** [comment]
That's great guys! Awesome work!

**Comment by alexmacavei** [comment]
Hey @jangalinski ! I'm having trouble getting CDI to scan my @Aggregate annotated class. Is there some extra registering needed? I'm not sure when AxonCdiExtension.processAggregate needs to be called, currently it's not in my context.

**Comment by zambrovski** [comment]
Hi Alex,

please check that you are using the right `@Aggregate` from `org.axonframework.cdi.stereotype`. It should be detected automatically - you don't need to call any methods from the extensions. I'll construct the example showing the basic usage.

Kind regards,

Simon

**Comment by alexmacavei** [comment]
Ya I'm using the right one, but I think I didn't have beans.xml with
discovery=all. Also intelliJ just decided to wipe clean my entire thing I
was almost done...I'll have to start over :/

Pe 7 ian. 2018 15:16, "Simon Zambrovski" <notifications@github.com> a scris:

**Comment by zambrovski** [comment]
An empty `beans.xml`should work too.
```
<!-- Marker file indicating CDI should be enabled -->
<beans xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
      http://java.sun.com/xml/ns/javaee
      http://java.sun.com/xml/ns/javaee/beans_1_0.xsd">
</beans>
```
