### ISSUE TITLE
 java.lang.IllegalArgumentException: Unknown entity

### ISSUE THREAD

**Issue by zambrovski** [holisticon/axon-cdi#13]
I'm getting this with TxAwareJPAEventStorageEngine:

java.lang.IllegalArgumentException: Unknown entity: org.axonframework.eventsourcing.eventstore.jpa.DomainEventEntry

Are these related I wonder?

**Comment by zambrovski** [comment]
If you are using EventSourcing, please remember to put the following code into your `persistence.xml`:

```
    <class>org.axonframework.eventsourcing.eventstore.jpa.DomainEventEntry</class>
    <class>org.axonframework.eventsourcing.eventstore.jpa.SnapshotEventEntry</class>
    <class>org.axonframework.eventhandling.saga.repository.jpa.AssociationValueEntry</class>
    <class>org.axonframework.eventhandling.saga.repository.jpa.SagaEntry</class>
    <properties>
      <property name="hibernate.hbm2ddl.auto" value="update"/>
    </properties>
```
and

**Comment by alexmacavei** [comment]
My example is finally working! Thanks for all the help. Example is here: 
https://github.com/alexmacavei/cqrs-example

**Comment by jangalinski** [comment]
@alexmacavei that's cool. cloned it and at least I can built it. How do I use it? Are you planning to move this to the axon-cdi/example area?

**Comment by alexmacavei** [comment]
Sure will do :)
You "mvn clean package" and then "java -jar target/cqrs-example-swarm.jar"

Pe 10 ian. 2018 11:28, "Jan Galinski" <notifications@github.com> a scris:
