### ISSUE TITLE
Fix BeanManager discovery in WELD SE environment

### ISSUE THREAD

**Issue by zambrovski** [holisticon/axon-cdi#4]
Current example is based on WELD SE implementation of CDI.

Access to JNDI is not available and should be fixed somehow to make example work.

In JNDI environments, the extension will work, but in WELD SE, the access to BeanManager can be provided by the container. The problem with it is that we have to deal with different access methods for the BeanManager. This access must be static (can't be Injected) because we require the BeanManager instance before CDI setup is finished.

**Comment by alexmacavei** [comment]
Hey, I've created an example myself and it seems to have a BeanManager creation issue. Might be related to this one, but I think this morning I didn't have this problem. Here's my example https://github.com/alexmacavei/cqrs-example

**Comment by zambrovski** [comment]
Hold on. This could be the problem. Maybe I screwed up the registration order.
